version: '3.8'

services:
  # Jenkins Master
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"      # Jenkins Web UI
      - "50000:50000"    # JNLP port for agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to run Docker builds
    environment:
      JENKINS_SLAVE_AGENT_PORT: 50000

  # Jenkins Slave (Agent)
  jenkins-agent:
    image: jenkins/inbound-agent
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=agent-1
      - JENKINS_SECRET=<TO-BE-REPLACED>
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-master

volumes:
  jenkins_home:
