apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.labelSelector }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
        - name: spring-petclinic
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
          command: ["java", "-jar", "/app/spring-petclinic.jar"]
#test
