apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.deploymentName }}
  labels:
    app: {{ .Values.mysql.label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.labelSelector }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.label }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
