apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  labels:
    app: {{ .Values.label }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: {{ .Values.labelSelector }}
